import os
import sys
import argparse
import spacy

__DEBUG = False
__dirname = os.path.dirname(__file__)

def trace(*args):
    if (__DEBUG): print(*args, file=sys.stderr)

def err(*args):
    print(*args, file=sys.stderr)

def makeCLI() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Use the model generated by model.sh."
    )
    p.add_argument(
        "-d", "--debug",
        type=bool, action=argparse.BooleanOptionalAction, default=False,
        help="Enables debug mode."
    )
    p.add_argument(
        "-i", "--input", 
        default=f"{__dirname}/outputs/model-best", 
        help="Options with choices."
    )

    return p

def test(ner, text):
    doc = ner(text)
    for ent in doc.ents:
        print(f"ENT: {ent.text} | LABEL: {ent.label_}")

def useModel(inputDir):
    ner = spacy.load(inputDir)

    # print("----- Test #1: Words of wisedom --------------")
    # test(ner, "O python é uma linguagem medíocre no melhor dos casos, e filtros da shell são infinitamente mais úteis.")

    print("----- Test #2: Tuga --------------")
    test(ner, "O Presidente da República Portuguesa foi eleito a 8 de Fevereiro de 2026, após dois sufrágios.")

    print("----- Test #2: Tuga 2 --------------")
    test(ner, "Calada, Cristina Ferreira era poeta.")

    print("----- Test #2: Tuga 3 --------------")
    test(
        ner, 
        "Em Gualtar, Braga, situam-se a Universidade do Minho, o Instituto Ibérico de Nanotecnologia, " 
            + "um McDonalds e o Centro Comercial Braga Parque."
    )
    # MISSING:
    # - Instituto Ibérico de Nanotecnologia
    # - McDonalds
    # - Centro Comercial
def main():
    global __DEBUG

    parser = makeCLI()
    args = parser.parse_args(sys.argv[1:])
    __DEBUG = args.debug

    trace("ARGS:", args)

    useModel(args.input)

if __name__ == "__main__":
    raise SystemExit(main())